server:
  port: 8020
spring:
  application:
    name: mango-config
  cloud:
    config:
      label: master  # git仓库分支
      server:
        git:
          uri: https://github.com/CHOutsider/mango-new.git  # 配置git仓库的地址
          search-paths: config-repo  # git仓库地址下的相对地址，可以配置多个，用,分割。
